### ISSUE TITLE
File wont open

### ISSUE THREAD

**Issue by Thel-Fett** [flxwed/flp-unlocker#1]
after using the script when you try to open the file back up in fl studio, fl studio will time out and no longer respond forcing you to close it
![Screenshot (6)](https://github.com/flxwed/flp-unlocker/assets/75282711/13c9757f-b8b0-4996-8f77-aac8b192ef8b)

**Comment by flxwed** [comment]
Please provide:
- FL Studio Version
- File (If comfortable)

**Comment by Thel-Fett** [comment]
fl studio version is 21, and the file is no longer with us

**Comment by Richardihn** [comment]
It's working in fl 20?

**Comment by sloppymewt** [comment]
they probably changed it little bit in fl 21, i included trial project and full version project in this zip file. please check it @flxwed 
[projects.zip](https://github.com/flxwed/flp-unlocker/files/14289264/projects.zip)

**Comment by flxwed** [comment]
> fl studio version is 21, and the file is no longer with us :(

Could you try creating another flp (empty project is fine) and sending it here?

**Comment by flxwed** [comment]
Marking as closed due to lack of response. If you are still experiencing this problem please reopen this issue.
