### ISSUE TITLE
thank you for this nice unlocker 

### ISSUE THREAD

**Issue by yasientra** [flxwed/flp-unlocker#2]
amazing thank you for this nice unlocker looking for this for years 

does it need fl studio could you repair fix this bug jusyt for me?
![Schermopname (1)](https://github.com/flxwed/flp-unlocker/assets/159732432/0cdd912d-e0d5-49c5-8269-22e8f8d8218c)

from the netherlands

yasien trabih

**Comment by yasientra** [comment]
do you have a steinberg unlocker

**Comment by flxwed** [comment]
You need to run the unlocker via command prompt with a path to the FLP as the first argument.

**Comment by flxwed** [comment]
Marking this as closed
